import { GoogleGenerativeAI, SchemaType } from '@google/generative-ai';
import { FilteredItem, ProcessedItem } from '../models/types';

// Tags are dynamically generated by the LLM now

export async function summarizeItemsGemini(items: FilteredItem[]): Promise<ProcessedItem[]> {
  if (items.length === 0) return [];

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

  // Using gemini-1.5-flash as per models.yaml default for gemini
  const model = genAI.getGenerativeModel({
    model: 'gemini-1.5-flash',
    generationConfig: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: SchemaType.OBJECT,
        properties: {
          processed_items: {
            type: SchemaType.ARRAY,
            items: {
              type: SchemaType.OBJECT,
              properties: {
                id: { type: SchemaType.STRING },
                llmSummary: { type: SchemaType.STRING },
                pmRelevance: { type: SchemaType.STRING },
                tags: {
                  type: SchemaType.ARRAY,
                  items: { type: SchemaType.STRING },
                },
              },
              required: ['id', 'llmSummary', 'pmRelevance', 'tags'],
            },
          },
        },
        required: ['processed_items'],
      },
    },
  });

  const prompt = `
You are an expert product manager analyzing a daily feed of news and new tools.
Your task is to review the following items, merge any duplicates (stories covering the same exact event or tool), and for each distinct item, provide:
1. A 1-line summary of the tool/news.
2. A 1-line explanation of why it's relevant to a PM's work.
3. Relevant tags: Generate 2-3 concise keyword tags that best categorize this item.

Input Items:
${JSON.stringify(
  items.map((i) => ({
    id: i.id,
    title: i.title,
    source: i.source,
    description: i.description?.substring(0, 1000) || '',
  })),
  null,
  2,
)}

Return a JSON object with a single key "processed_items" containing an array of objects.
Each object must have the following keys:
- "id": The ID of the item (if you merged multiple, pick the one from the most reliable source).
- "llmSummary": The 1-line summary.
- "pmRelevance": The 1-line explanation of why it matters to a PM.
- "tags": Array of 2-3 dynamically generated keyword tags as strings.
`;

  try {
    const result = await model.generateContent(prompt);
    const content = result.response.text();

    if (!content) throw new Error('No content returned from Gemini');

    const parsed = JSON.parse(content);
    const processedMap = new Map<string, any>();

    for (const p of parsed.processed_items || []) {
      processedMap.set(p.id, p);
    }

    const finalItems: ProcessedItem[] = [];
    for (const item of items) {
      if (processedMap.has(item.id)) {
        const p = processedMap.get(item.id);
        finalItems.push({
          ...item,
          llmSummary: p.llmSummary,
          pmRelevance: p.pmRelevance,
          tags: p.tags || [],
        });
      }
    }
    return finalItems;
  } catch (error) {
    console.error('Summarization failed in Gemini', error);
    return [];
  }
}
